/** Copy for the admin moderation screens. */
export const MODERATION_COPY = {
  title: "Admin",
  tabs: {
    members: "Members",
    reports: "Reports",
    verification: "Verification",
    blocklist: "Block list",
  },
  reports: {
    statuses: { open: "Open", resolved: "Resolved", dismissed: "Dismissed" },
    loading: "Loading reports…",
    empty: "Nothing to review.",
    reportedBy: "Reported by",
    deletedAccount: "a deleted account",
    details: "Their note",
    evidence: "Last messages in the chat",
    noEvidence: "No chat attached.",
    reported: "Reported",
    openMember: "Open member",
    resolve: "Resolve",
    dismiss: "Dismiss",
    photo: "Photo",
  },
  verification: {
    intro:
      "Identity checks Didit couldn't settle alone. Compare the photo members see with the original upload and the Didit session, then decide.",
    loading: "Loading verifications…",
    empty: "No verifications to review.",
    refresh: "Refresh (photo links last 10 minutes)",
    noName: "Unnamed member",
    openMember: "Open member",
    photo: "Profile photo (as members see it)",
    original: "Original upload",
    session: "Didit session",
    why: "Why it needs a person",
    checksHeading: "Checks",
    passed: "Passed",
    notPassed: "Not passed",
    approve: "Approve",
    reject: "Reject",
    cannotApprove: "The ID checks didn't pass, so this can only be rejected.",
    checks: {
      governmentId: "Government ID",
      liveness: "Live selfie",
      idFace: "Selfie matches ID",
      profileFace: "Selfie matches profile photo",
      dateOfBirth: "Birth date matches profile",
      gender: "Gender matches profile",
      country: "ID country matches profile",
    },
    reasons: {
      PROFILE_PHOTO_FACE_MATCH_REQUIRED: "The profile photo match needs a person to check it",
      PROFILE_PHOTO_MATCH_INCONCLUSIVE: "The selfie and profile photo didn't clearly match",
      LOW_FACE_MATCH_SIMILARITY: "The selfie and profile photo didn't look alike enough",
      PROFILE_PHOTO_MATCH_UNAVAILABLE: "The profile photo comparison wasn't available",
      PROFILE_PHOTO_MATCH_INTERRUPTED: "The profile photo comparison was interrupted",
      PROFILE_PHOTO_MATCH_CONSENT_REQUIRED: "No consent on record for the photo comparison",
      PROFILE_PHOTO_CAPTURE_UNAVAILABLE: "Didit didn't return a selfie to compare",
      PROFILE_CHANGED_DURING_VERIFICATION: "They changed their profile during the check",
      ID_COUNTRY_UNCONFIRMED: "The ID's country doesn't match their nationality or country",
      IDENTITY_ON_ANOTHER_ACCOUNT: "This ID is already verified on another account",
    } as Record<string, string>,
    decision: {
      approveTitle: "Approve this verification?",
      approveBody:
        "They get the verified badge. Only approve if the selfie in Didit and the profile photo are clearly the same person, and the ID's country makes sense for them.",
      rejectTitle: "Reject this verification?",
      rejectBody: "The attempt counts as failed. They can try again if they have attempts left.",
      evidenceLabel: "Evidence reference (e.g. the Didit session)",
      reasonLabel: "Reason (at least 10 characters, kept in the audit log)",
    },
    notices: {
      approved: "Approved. They're verified.",
      rejected: "Rejected.",
    },
  },
  denied: "This area is for admins only.",
  checking: "Checking access…",
  search: {
    placeholder: "Name, @username, email or phone",
    newest: "Newest members",
    results: (q: string) => `Results for “${q}”`,
    empty: "No members match.",
  },
  member: {
    back: "All members",
    posts: "Posts",
    noPosts: "No posts.",
    rules: "Sign-up rules for this member",
    protected: "Admin accounts can't be blocked or deleted here.",
    verification: "Identity verification",
    verificationStatuses: {
      not_started: "Not verified",
      pending: "Checking with Didit",
      failed: "Last check didn't pass",
      manual_review: "Waiting for review",
      verified: "Verified",
      rejected: "Rejected",
      revoked: "Revoked",
    },
    attemptsUsed: (n: number) => `${n} of 3 attempts used`,
    actions: {
      block: "Block",
      unblock: "Unblock",
      deletePosts: "Delete all posts",
      deleteAccount: "Delete account",
      deletePost: "Delete",
      revokeVerification: "Revoke verification",
      reopenVerification: "Allow verifying again",
    },
  },
  dialogs: {
    cancel: "Cancel",
    reasonLabel: "Reason (kept in the moderation log)",
    block: {
      title: "Block this member?",
      body: "They're signed out everywhere and can't sign in again. Their email and phone can't be used to sign up, and the IPs they used are flagged. Their profile and posts disappear from Kinkord.",
      checkbox: "Also delete all their posts",
      confirm: "Block",
    },
    unblock: {
      title: "Unblock this member?",
      body: "They can sign in again, and the sign-up rules written when they were blocked are removed.",
      confirm: "Unblock",
    },
    deletePosts: {
      title: "Delete all their posts?",
      body: "Every post and the photos in it are removed. This can't be undone.",
      confirm: "Delete posts",
    },
    deletePost: {
      title: "Delete this post?",
      body: "The post and its photos are removed. This can't be undone.",
      confirm: "Delete post",
    },
    revokeVerification: {
      title: "Revoke their verification?",
      body: "Their verified badge goes, and any check in progress stops. They can't verify again until an admin allows it.",
      confirm: "Revoke",
    },
    reopenVerification: {
      title: "Let them verify again?",
      body: "They get a fresh set of 3 attempts.",
      confirm: "Allow",
    },
    deleteAccount: {
      title: "Delete this account?",
      body: "The account, posts, comments, likes, follows and photos are permanently deleted. This can't be undone.",
      checkbox: "Also stop them signing up again with the same email or phone",
      typeToConfirm: (phrase: string) => `Type ${phrase} to confirm`,
      confirm: "Delete account",
    },
  },
  notices: {
    blocked: (posts: number) =>
      posts > 0
        ? `Blocked, and ${posts} posts deleted.`
        : "Blocked. They've been signed out everywhere.",
    unblocked: "Unblocked.",
    postsDeleted: (n: number) => `${n} ${n === 1 ? "post" : "posts"} deleted.`,
    postDeleted: "Post deleted.",
    verificationRevoked: "Verification revoked.",
    verificationReopened: "They can verify again.",
  },
  blocklist: {
    intro:
      "Sign-ups and verification codes are checked against this list. Blocked entries are refused; flagged ones are let through and logged for you to review.",
    kindLabel: "Type",
    valueLabel: "Value",
    actionLabel: "What happens",
    reasonLabel: "Reason (optional)",
    add: "Add to list",
    remove: "Remove",
    empty: "The list is empty.",
    kinds: [
      {
        value: "email",
        label: "Email",
        hint: "e.g. name@gmail.com — dot and +tag variants are caught",
      },
      { value: "phone", label: "Phone", hint: "e.g. 0803 123 4567 or +2348031234567" },
      {
        value: "name",
        label: "Name contains",
        hint: "a rare name, e.g. a surname — flag is safer",
      },
      { value: "ip", label: "IP address", hint: "mobile IPs are shared — flag, don't block" },
    ],
    actions: [
      { value: "block", label: "Block" },
      { value: "flag", label: "Flag for review" },
    ],
  },
  settingsEntry: "Admin",
} as const;
