/** Nigerian LGAs / popular areas per state, provided by the product team.
 *  Every list ends with the catch-all option so nobody is blocked. */
export const REGION_NOT_LISTED = "My region is not listed";

export const NG_LGAS: Record<string, readonly string[]> = {
  Abia: [
    "Aba",
    "Alayi",
    "Ariaria",
    "Arochukwu",
    "Bende",
    "Ikwuano",
    "Isuikwuato",
    "Mbawsi",
    "Ngwa",
    "Nkporo",
    "Obingwa",
    "Ohafia",
    "Osisioma",
    "Ovim",
    "Ukwa",
    "Umudike",
    "Umuahia",
    "Umunneochi",
    "Ututu",
    "Uzuakoli",
    "My region is not listed",
  ],
  Adamawa: [
    "Demsa",
    "Fufore",
    "Ganye",
    "Girei",
    "Gombi",
    "Gulak",
    "Guyuk",
    "Hong",
    "Jada",
    "Jimeta",
    "Maiha",
    "Madagali",
    "Mayo-Belwa",
    "Michika",
    "Mubi",
    "Numan",
    "Shelleng",
    "Song",
    "Toungo",
    "Yola",
    "My region is not listed",
  ],
  "Akwa Ibom": [
    "Abak",
    "Eket",
    "Essene",
    "Etinan",
    "Eastern Obolo",
    "Ibiono",
    "Ibesikpo Asutan",
    "Ika",
    "Ikot Abasi",
    "Ikot Ekpene",
    "Ini",
    "Itu",
    "Mkpat-Enin",
    "Nsit Ibom",
    "Onna",
    "Opobo",
    "Oron",
    "Oruk Anam",
    "Ukaana",
    "Uyo",
    "My region is not listed",
  ],
  Anambra: [
    "Abagana",
    "Adazi",
    "Aguata",
    "Atani",
    "Awka",
    "Awka-Etiti",
    "Dunukofia",
    "Ekwulobia",
    "Enugwu-Ukwu",
    "Ihiala",
    "Nkpor",
    "Nnewi",
    "Obosi",
    "Ogidi",
    "Onitsha",
    "Otuocha",
    "Ozubulu",
    "Oyi",
    "Umunze",
    "Umuchu",
    "My region is not listed",
  ],
  Bauchi: [
    "Alkaleri",
    "Azare",
    "Bauchi",
    "Bogoro",
    "Dambam",
    "Darazo",
    "Dass",
    "Gamawa",
    "Ganjuwa",
    "Giade",
    "Itas",
    "Jama'are",
    "Katagum",
    "Kirfi",
    "Misau",
    "Ningi",
    "Tafawa Balewa",
    "Toro",
    "Warji",
    "Zaki",
    "My region is not listed",
  ],
  Bayelsa: [
    "Agge",
    "Amassama",
    "Brass",
    "Ekeremor",
    "Ekeremor Town",
    "Igbogene",
    "Kaiama",
    "Kolokuma",
    "Nembe",
    "Nembe City",
    "Odi",
    "Ogbia",
    "Ogbia Town",
    "Okolobiri",
    "Opokuma",
    "Sagbama",
    "Sagbama Town",
    "Sampou",
    "Twon-Brass",
    "Yenagoa",
    "My region is not listed",
  ],
  Benue: [
    "Adikpo",
    "Adoka",
    "Aliade",
    "Buruku",
    "Gbajimba",
    "Gboko",
    "Igumale",
    "Katsina-Ala",
    "Lessel",
    "Makurdi",
    "Naka",
    "Ogbadibo",
    "Oju",
    "Okpoga",
    "Otukpa",
    "Otukpo",
    "Ugbokolo",
    "Vandeikya",
    "Wannune",
    "Zaki-Biam",
    "My region is not listed",
  ],
  Borno: [
    "Askira",
    "Bama",
    "Banki",
    "Biu",
    "Chibok",
    "Damboa",
    "Dikwa",
    "Gamboru",
    "Gubio",
    "Gwoza",
    "Kaga",
    "Konduga",
    "Kwaya Kusar",
    "Kukawa",
    "Maiduguri",
    "Magumeri",
    "Marte",
    "Monguno",
    "Ngala",
    "My region is not listed",
  ],
  "Cross River": [
    "Abi",
    "Adim",
    "Akamkpa",
    "Akpabuyo",
    "Bakassi",
    "Bekwarra",
    "Biase",
    "Boki",
    "Calabar",
    "Etung",
    "Ikom",
    "Itigidi",
    "Obubra",
    "Obudu",
    "Odukpani",
    "Ogoja",
    "Okpoma",
    "Sankwala",
    "Ugep",
    "Yakurr",
    "My region is not listed",
  ],
  Delta: [
    "Abraka",
    "Agbarho",
    "Agbor",
    "Asaba",
    "Bomadi",
    "Burutu",
    "Effurun",
    "Issele-Uku",
    "Koko",
    "Kwale",
    "Obiaruku",
    "Oghara",
    "Oleh",
    "Ozoro",
    "Patani",
    "Sapele",
    "Ughelli",
    "Uvwie",
    "Warri",
    "Isoko",
    "My region is not listed",
  ],
  Ebonyi: [
    "Abakaliki",
    "Afikpo",
    "Akaeze",
    "Amasiri",
    "Edda",
    "Effium",
    "Enyibichiri",
    "Ezza",
    "Ezzamgbo",
    "Ikwo",
    "Ishiagu",
    "Ishielu",
    "Izzi",
    "Ivo",
    "Nkalagu",
    "Nkomoro",
    "Ohaukwu",
    "Okposhi",
    "Onueke",
    "Uburu",
    "My region is not listed",
  ],
  Edo: [
    "Abudu",
    "Afuze",
    "Agenebode",
    "Auchi",
    "Benin City",
    "Ehor",
    "Ekpoma",
    "Fugar",
    "Igarra",
    "Igueben",
    "Iguobazuwa",
    "Irrua",
    "Jattu",
    "Okada",
    "Owan",
    "Sabongida-Ora",
    "Siluko",
    "Ubiaja",
    "Udo",
    "Uromi",
    "My region is not listed",
  ],
  Ekiti: [
    "Ado-Ekiti",
    "Aramoko",
    "Ayede",
    "Efon-Alaaye",
    "Emure",
    "Erinmope",
    "Ido-Osi",
    "Ifaki",
    "Igbara-Odo",
    "Ijero",
    "Ikere",
    "Ikole",
    "Ilawe",
    "Ise",
    "Iyin",
    "Ode",
    "Omuo",
    "Otun",
    "Oye",
    "Ila-Orangun",
    "My region is not listed",
  ],
  Enugu: [
    "9th Mile",
    "Abakpa",
    "Achi",
    "Adani",
    "Agbani",
    "Amagunze",
    "Awgu",
    "Eha-Amufu",
    "Emene",
    "Enugu",
    "Ezeagu",
    "Ibagwa-Aka",
    "Nkanu",
    "Ngwo",
    "Nsukka",
    "Obollo-Afor",
    "Oji River",
    "Ozalla",
    "Udi",
    "Nike",
    "My region is not listed",
  ],
  Gombe: [
    "Akko",
    "Bajoga",
    "Balanga",
    "Bambam",
    "Billiri",
    "Dadin Kowa",
    "Deba",
    "Dukku",
    "Funakaye",
    "Garko",
    "Gombe",
    "Kalshingi",
    "Kaltungo",
    "Kuri",
    "Liji",
    "Nafada",
    "Pindiga",
    "Talasse",
    "Ture",
    "Yamaltu",
    "My region is not listed",
  ],
  Imo: [
    "Egbema",
    "Ehime Mbano",
    "Ezinihitte",
    "Ideato",
    "Ikeduru",
    "Ihitte Uboma",
    "Isu",
    "Mbaise",
    "Mbaitoli",
    "Ngor Okpala",
    "Njaba",
    "Nkwerre",
    "Obowo",
    "Oguta",
    "Ohaji",
    "Okigwe",
    "Orlu",
    "Oru",
    "Owerri",
    "Umuaka",
    "My region is not listed",
  ],
  Jigawa: [
    "Auyo",
    "Babura",
    "Birnin Kudu",
    "Dutse",
    "Garki",
    "Gwaram",
    "Gumel",
    "Hadejia",
    "Jahun",
    "Kafin Hausa",
    "Kaugama",
    "Kazaure",
    "Maigatari",
    "Miga",
    "Ringim",
    "Roni",
    "Sule Tankarkar",
    "Taura",
    "Wudil",
    "Yankwashi",
    "My region is not listed",
  ],
  Kaduna: [
    "Birnin Gwari",
    "Giwa",
    "Ikara",
    "Jema'a",
    "Kachia",
    "Kagoro",
    "Kajuru",
    "Kafanchan",
    "Kaduna",
    "Kaura",
    "Kubau",
    "Kudan",
    "Makarfi",
    "Sabon Gari",
    "Saminaka",
    "Soba",
    "Zangon Kataf",
    "Zaria",
    "My region is not listed",
  ],
  Kano: [
    "Bichi",
    "Dambatta",
    "Dawakin Tofa",
    "Gabasawa",
    "Gaya",
    "Gezawa",
    "Kano",
    "Karaye",
    "Kibiya",
    "Kiru",
    "Kura",
    "Madobi",
    "Minjibir",
    "Rano",
    "Rimin Gado",
    "Sumaila",
    "Takai",
    "Tofa",
    "Ungogo",
    "Wudil",
    "My region is not listed",
  ],
  Katsina: [
    "Bakori",
    "Batsari",
    "Charanchi",
    "Dan Musa",
    "Daura",
    "Dutsin-Ma",
    "Funtua",
    "Jibiya",
    "Kafur",
    "Kaita",
    "Kankara",
    "Katsina",
    "Malumfashi",
    "Mani",
    "Mashi",
    "Matazu",
    "Musawa",
    "Rimi",
    "Safana",
    "Zango",
    "My region is not listed",
  ],
  Kebbi: [
    "Aleiro",
    "Argungu",
    "Augie",
    "Bagudo",
    "Birnin Kebbi",
    "Bunza",
    "Dakingari",
    "Fakai",
    "Jega",
    "Kalgo",
    "Kamba",
    "Koko",
    "Maiyama",
    "Ngaski",
    "Sakaba",
    "Shanga",
    "Suru",
    "Wasagu",
    "Yauri",
    "Zuru",
    "My region is not listed",
  ],
  Kogi: [
    "Adavi",
    "Ajaokuta",
    "Anyigba",
    "Ankpa",
    "Bassa",
    "Dekina",
    "Egbe",
    "Ibaji",
    "Idah",
    "Igalamela",
    "Isanlu",
    "Kabba",
    "Koton Karfe",
    "Lokoja",
    "Mopa-Muro",
    "Obajana",
    "Ofu",
    "Okene",
    "Olamaboro",
    "Yagba",
    "My region is not listed",
  ],
  Kwara: [
    "Ajase-Ipo",
    "Arandun",
    "Bacita",
    "Bode Saadu",
    "Esie",
    "Erin-Ile",
    "Igbaja",
    "Iloffa",
    "Ilorin",
    "Jebba",
    "Kaiama",
    "Lafiagi",
    "Offa",
    "Okuta",
    "Omu-Aran",
    "Oro",
    "Owu-Isin",
    "Patigi",
    "Share",
    "Shonga",
    "My region is not listed",
  ],
  Lagos: [
    "Agege",
    "Ajah",
    "Alaba",
    "Alimosho",
    "Amuwo-Odofin",
    "Apapa",
    "Badagry",
    "Bariga",
    "Berger",
    "Chevron",
    "Egbeda",
    "Epe",
    "Eric Moore",
    "Festac",
    "Gbagada",
    "Ikeja",
    "Ikorodu",
    "Ikoyi",
    "Ijegun",
    "Ijeshatedo",
    "Ijora",
    "Ilupeju",
    "Ipaja",
    "Isolo",
    "Jibowu",
    "Ketu",
    "Kosofe",
    "Lagos Island",
    "Lekki",
    "Maryland",
    "Mushin",
    "Ogba",
    "Ogudu",
    "Ojota",
    "Ojo",
    "Oshodi",
    "Palmgrove",
    "Sangotedo",
    "Shomolu",
    "Surulere",
    "Tejuosho",
    "Victoria Island",
    "Yaba",
    "Ibeju-Lekki",
    "Itire",
    "Jakande",
    "Magodo",
    "Mile 2",
    "Obalende",
    "Oniru",
    "My region is not listed",
  ],
  Nasarawa: [
    "Akwanga",
    "Assakio",
    "Awe",
    "Doma",
    "Garaku",
    "Gitata",
    "Karu",
    "Keana",
    "Keffi",
    "Kokona",
    "Lafia",
    "Mararaba",
    "Masaka",
    "Nasarawa",
    "Obi",
    "Panda",
    "Shabu",
    "Toto",
    "Uke",
    "Wamba",
    "My region is not listed",
  ],
  Niger: [
    "Agaie",
    "Bida",
    "Edati",
    "Gbako",
    "Gurara",
    "Kagara",
    "Katcha",
    "Kontagora",
    "Lapai",
    "Mariga",
    "Mashegu",
    "Minna",
    "Mokwa",
    "Munya",
    "New Bussa",
    "Paikoro",
    "Rijau",
    "Shiroro",
    "Suleja",
    "Wushishi",
    "My region is not listed",
  ],
  Ogun: [
    "Abeokuta",
    "Abeokuta North",
    "Abeokuta South",
    "Ado-Odo",
    "Ago-Iwoye",
    "Ayetoro",
    "Ewekoro",
    "Ijebu-Igbo",
    "Ijebu-Ode",
    "Ilaro",
    "Imeko",
    "Ipokia",
    "Iperu",
    "Isara",
    "Obafemi Owode",
    "Odogbolu",
    "Ota",
    "Owode",
    "Remo",
    "Sagamu",
    "My region is not listed",
  ],
  Ondo: [
    "Ajagba",
    "Akoko",
    "Akure",
    "Araromi-Obu",
    "Ese-Odo",
    "Igbokoda",
    "Idanre",
    "Ifon",
    "Ikare",
    "Ikun",
    "Ilaje",
    "Irele",
    "Isua",
    "Oba-Akoko",
    "Oka-Akoko",
    "Okitipupa",
    "Ondo",
    "Ore",
    "Owo",
    "Supare",
    "My region is not listed",
  ],
  Osun: [
    "Ede",
    "Ejigbo",
    "Esa-Oke",
    "Erin-Osun",
    "Gbongan",
    "Ifon",
    "Ile-Ife",
    "Ila-Orangun",
    "Ilobu",
    "Ilesa",
    "Ipetumodu",
    "Ijebu-Jesa",
    "Ikire",
    "Ikirun",
    "Iwo",
    "Modakeke",
    "Ode-Omu",
    "Okuku",
    "Osogbo",
    "My region is not listed",
  ],
  Oyo: [
    "Egbeda",
    "Eruwa",
    "Fiditi",
    "Ibadan",
    "Ibarapa",
    "Ido",
    "Igboho",
    "Igbo-Ora",
    "Iseyin",
    "Kisi",
    "Lagelu",
    "Lalupon",
    "Moniya",
    "Ona-Ara",
    "Ogbomoso",
    "Omi-Adio",
    "Oluyole",
    "Oyo",
    "Saki",
    "Shaki",
    "My region is not listed",
  ],
  Plateau: [
    "Barkin Ladi",
    "Bassa",
    "Bokkos",
    "Bukuru",
    "Jos",
    "Jos East",
    "Jos South",
    "Kanke",
    "Kanam",
    "Langtang",
    "Mangu",
    "Mikang",
    "Pankshin",
    "Quan'Pan",
    "Riyom",
    "Shendam",
    "Vom",
    "Wase",
    "Wukari",
    "My region is not listed",
  ],
  Rivers: [
    "Abonnema",
    "Abua",
    "Ahoada",
    "Andoni",
    "Bori",
    "Bonny",
    "Buguma",
    "Degema",
    "Eleme",
    "Emohua",
    "Etche",
    "Ikwerre",
    "Khana",
    "Obio-Akpor",
    "Okrika",
    "Omoku",
    "Opobo",
    "Port Harcourt",
    "Tai",
    "Oyigbo",
    "My region is not listed",
  ],
  Sokoto: [
    "Binji",
    "Bodinga",
    "Dange",
    "Gada",
    "Goronyo",
    "Gwadabawa",
    "Illela",
    "Isa",
    "Kebbe",
    "Kware",
    "Rabah",
    "Shagari",
    "Silame",
    "Sokoto",
    "Tambuwal",
    "Tangaza",
    "Tureta",
    "Wamakko",
    "Wurno",
    "Yabo",
    "My region is not listed",
  ],
  Taraba: [
    "Ardo-Kola",
    "Baissa",
    "Bali",
    "Chanchanji",
    "Donga",
    "Gassol",
    "Gembu",
    "Ibi",
    "Jalingo",
    "Karim Lamido",
    "Kpanti",
    "Kurmi",
    "Lau",
    "Mayo-Ranewo",
    "Mutum Biyu",
    "Serti",
    "Takum",
    "Wukari",
    "Yorro",
    "Zing",
    "My region is not listed",
  ],
  Yobe: [
    "Bade",
    "Bursari",
    "Damaturu",
    "Dapchi",
    "Fika",
    "Fune",
    "Gashua",
    "Geidam",
    "Gulani",
    "Gujba",
    "Jakusko",
    "Karasuwa",
    "Machina",
    "Nangere",
    "Nguru",
    "Potiskum",
    "Tarmuwa",
    "Yunusari",
    "Yusufari",
    "My region is not listed",
  ],
  Zamfara: [
    "Anka",
    "Bakura",
    "Birnin Magaji",
    "Bungudu",
    "Bukkuyum",
    "Chafe",
    "Dansadau",
    "Gummi",
    "Gusau",
    "Kaura Namoda",
    "Kwatarkwashi",
    "Magami",
    "Maradun",
    "Maru",
    "Mada",
    "Mutunji",
    "Shinkafi",
    "Talata Mafara",
    "Tsafe",
    "Zurmi",
    "My region is not listed",
  ],
  "FCT Abuja": [
    "Abuja",
    "Asokoro",
    "Bwari",
    "Dei-Dei",
    "Dutse",
    "Galadimawa",
    "Garki",
    "Gwarinpa",
    "Jabi",
    "Jikwoyi",
    "Karmo",
    "Karu",
    "Kubwa",
    "Kuje",
    "Lugbe",
    "Maitama",
    "Mpape",
    "Nyanya",
    "Wuse",
    "Gwagwalada",
    "My region is not listed",
  ],
};
