export const NOTIFICATIONS_COPY = {
  title: "Notifications",
  subtitle: "Your latest messages and community activity.",
  all: "All",
  comments: "Comments",
  mentions: "Mentions",
  search: "Search notifications",
  menu: "Notification options",
  markRead: "Mark as read",
  openNotification: "Open notification",
  unread: "Unread",
  unreadLabel: "Unread notification",
  markAll: "Mark all as read",
  marking: "Marking as read…",
  loading: "Loading notifications…",
  loadingMore: "Loading more…",
  loadMore: "Load more notifications",
  emptyTitle: "You’re all caught up",
  emptyBody: "New messages, followers and activity on your posts will appear here.",
  emptySearch: "No matching notifications.",
  emptyComments: "Comments on your posts will appear here.",
  emptyMentions: "No mention notifications yet.",
  deleteNotification: "Delete notification",
  reportNotification: "Report notification",
  deleteError: "Could not delete this notification. Please try again.",
  reportIntro: "Choose a reason. A copy of this notification will be sent to our moderation team.",
  reportError: "Could not send your report. Please try again.",
  close: "Close",
  categories: "Notification categories",
  emptyUnread: "No unread notifications. You’re up to date.",
  error: "Could not load notifications. Please try again.",
  readError: "Could not mark this notification as read. Please try again.",
  readAllError: "Could not mark notifications as read. Please try again.",
  retry: "Try again",
  refresh: "Refresh notifications",
  open: "Opening…",
} as const;
