export const LAUNCH_COUNTRIES = [
  { code: "NG", name: "Nigeria", flag: "🇳🇬", dialCode: "+234" },
] as const;

export const PHONE_COUNTRY_CODES = [
  { code: "NG", dialCode: "+234", flag: "🇳🇬" },
  { code: "US", dialCode: "+1", flag: "🇺🇸" },
  { code: "GB", dialCode: "+44", flag: "🇬🇧" },
  { code: "ZA", dialCode: "+27", flag: "🇿🇦" },
  { code: "KE", dialCode: "+254", flag: "🇰🇪" },
  { code: "GH", dialCode: "+233", flag: "🇬🇭" },
] as const;

export const NG_STATES = [
  "Abia",
  "Adamawa",
  "Akwa Ibom",
  "Anambra",
  "Bauchi",
  "Bayelsa",
  "Benue",
  "Borno",
  "Cross River",
  "Delta",
  "Ebonyi",
  "Edo",
  "Ekiti",
  "Enugu",
  "FCT Abuja",
  "Gombe",
  "Imo",
  "Jigawa",
  "Kaduna",
  "Kano",
  "Katsina",
  "Kebbi",
  "Kogi",
  "Kwara",
  "Lagos",
  "Nasarawa",
  "Niger",
  "Ogun",
  "Ondo",
  "Osun",
  "Oyo",
  "Plateau",
  "Rivers",
  "Sokoto",
  "Taraba",
  "Yobe",
  "Zamfara",
] as const;

export const KINK_ROLES = [
  "Dominant",
  "Submissive",
  "Switch",
  "Top",
  "Bottom",
  "Master",
  "Mistress",
  "Slave",
  "Pet",
  "Owner",
  "Handler",
  "Brat",
  "Brat Tamer",
  "Sadist",
  "Masochist",
  "Rigger",
  "Rope Bunny",
  "Voyeur",
  "Exhibitionist",
  "Primal",
  "Caregiver",
  "Little",
  "Curious",
] as const;

export const SIGNUP_STEP_LABELS = [
  "Country",
  "Account",
  "Verification",
  "Profile",
  "Welcome",
] as const;
