export const Routes = {
  home: "/",
  kinkopedia: "/kinkopedia",
  about: "/about",
  contact: "/contact",
  invest: "/invest",
  lectures: "/lectures",
  lecture: (slug: string) => `/lectures/${slug}`,
  admin: "/admin",
  adminLogin: "/admin/login",
  adminLecturesNew: "/admin/lectures/new",
  adminLectureEdit: (id: string) => `/admin/lectures/${id}/edit`,
  signup: "/signup",
  login: "/login",
  appHome: "/home",
  messages: "/messages",
  settings: "/settings",
  profileEdit: "/profile/edit",
  forgotPassword: "/forgot-password",
  resetPassword: "/reset-password",
  verifyEmail: "/verify-email",
  profile: "/profile",
} as const;
