export const Routes = {
  home: "/",
  kinkopedia: "/kinkopedia",
  about: "/about",
  contact: "/contact",
  invest: "/invest",
  lectures: "/lectures",
  lecture: (slug: string) => `/lectures/${slug}`,
  admin: "/admin",
  adminLogin: "/admin/login",
  adminLecturesNew: "/admin/lectures/new",
  adminLectureEdit: (id: string) => `/admin/lectures/${id}/edit`,
  signup: "/signup",
  login: "/login",
  appHome: "/home",
  messages: "/messages",
  settings: "/settings",
  profileEdit: "/profile/edit",
  forgotPassword: "/forgot-password",
  resetPassword: "/reset-password",
  verifyEmail: "/verify-email",
  profile: "/profile",
  // Members directory: country -> state -> members in that state.
  members: "/members",
  membersCountry: (country: string) => `/members/${country.toLowerCase()}`,
  membersState: (country: string, state: string) =>
    `/members/${country.toLowerCase()}/${encodeURIComponent(state)}`,
  /** Another member's public profile. */
  member: (username: string) => `/u/${encodeURIComponent(username.replace(/^@/, ""))}`,
  notifications: "/notifications",
} as const;
