/** Copy for the Silver Premium screens (Figma wTTGnyZzV4lAhvEMVz7UDJ: 2:179/2:2, 46:2/46:135, 48:348/48:111). */
export const SUBSCRIPTION_COPY = {
  back: "Back",
  loading: "Loading…",
  securePayment: "Secure Payment",
  periods: { monthly: "Monthly", yearly: "Yearly" },
  per: { monthly: "/ month", yearly: "/ year" },
  upgrade: {
    title: "Unlock More with Silver",
    subtitle:
      "Get more freedom, more connection and more control. Upgrade to a premium plan and experience Kinkord to the fullest.",
    plan: {
      basic: { title: "You're on Kinkord Basic", body: "Enjoy the basics. Upgrade for more." },
      silver: {
        title: "You're on Silver Premium",
        body: (until: string) => `Active until ${until}.`,
        /** Where the member's Silver check stands, under the plan. */
        check: {
          shown: "Your Silver check shows on your profile.",
          held: {
            name: "Your check is hidden while we look at your new name.",
            username: "Your check is hidden while we look at your new username.",
            photo: "Your check is hidden while we look at your new photo.",
            admin: "Your check is hidden after a review by our team.",
          },
          photos: "Add a profile photo and a cover photo to show your check.",
          newAccount: (date: string) => `Your check shows from ${date}.`,
        },
      },
      pending: {
        title: "Your payment is waiting",
        body: "Finish your transfer, or send us your proof.",
      },
      review: {
        title: "We're checking your payment",
        body: "We'll let you know as soon as it's confirmed.",
      },
      rejected: {
        title: "We couldn't confirm your payment",
        body: (reason: string) => reason,
      },
    },
    silverLabel: "SILVER PREMIUM",
    crestAlt: "Silver crest",
    medalAlt: "Silver Premium",
    headline: ["More Features.", "More You."],
    tagline: "Unlock the full Kinkord experience with Silver.",
    features: [
      { icon: "pencil", title: "Long-form posts", body: "Up to 25,000 characters" },
      { icon: "chat", title: "More conversations", body: "Send & receive more messages daily" },
      { icon: "gift", title: "Receive & send gifts", body: "Kinkcoins, virtual gifts & more" },
      { icon: "shield", title: "Verified-only messages", body: "Choose who can message you" },
      { icon: "globe", title: "International messaging", body: "Connect globally" },
      { icon: "ban", title: "Ad-free experience", body: "No ads, just Kinkord" },
    ],
    /** The full list behind "See all 15 Silver benefits"; the link shows once it's longer than what's above. */
    allBenefits: [] as Array<{ title: string; body: string }>,
    seeAll: (n: number) => `See all ${n} Silver benefits`,
    save: (percent: number) => `Save ${percent}%`,
    gold: {
      label: "GOLD PREMIUM",
      body: "Even more power. Coming soon.",
      medalAlt: "Gold Premium",
    },
    diamond: {
      label: "DIAMOND PREMIUM",
      body: "The ultimate Kinkord experience. Coming soon.",
      bodyWide: "The ultimate Kinkord experience",
      medalAlt: "Diamond Premium",
    },
    comingSoon: "Coming Soon",
    slogan: "BETTER CONNECTIONS. BIGGER OPPORTUNITIES.",
    cta: {
      upgrade: "Upgrade to Silver",
      extend: "Extend Silver",
      resume: "Continue your payment",
      review: "Payment under review",
      unavailable: "Payments open soon",
      starting: "Starting…",
    },
  },
  pay: {
    title: ["Get Silver ", "Premium"],
    subtitle: "More features. More connection. Upgrade and unlock the full Kinkord experience.",
    savePill: (percent: number) => `SAVE ${percent}%`,
    approx: (amount: string) => `≈ ${amount}`,
    amountTitle: "Payment Amount",
    amountBody: "Transfer the exact amount below. Do not add more or less.",
    expiresIn: "Expires in",
    usdApprox: (amount: string) => `(≈ ${amount})`,
    copy: "Copy",
    copied: "Copied",
    uniqueTitle: "Your unique payment amount",
    uniqueBody: "Do not modify this amount.",
    bankTitle: "Bank Transfer Details",
    bankBody: "Transfer to the account below using the exact amount.",
    bankName: "Bank Name",
    accountName: "Account Name",
    accountNumber: "Account Number",
    referenceTitle: "Your Payment Reference / Code",
    referenceBody: "This code is linked to your account. Use it when making the transfer.",
    confirm: "I have completed the bank transfer using the details above.",
    cta: "I've Completed the Payment",
    switching: "Switching…",
    expired: {
      title: "Time's up",
      body: "This amount is no longer held for you. If you've already paid, send us your proof; if not, start again.",
      restart: "Start again",
      paid: "I've already paid",
    },
  },
  proof: {
    title: ["Submit Your", "Payment Proof"],
    subtitle:
      "Upload your payment receipt and enter the account details used to make this transfer.",
    detailsTitle: "Payment Details",
    detailsBody: "Make sure these details match your payment receipt.",
    referenceLabel: "Payment Reference / Code",
    amountLabel: "Amount Paid (₦)",
    editable: "Editable",
    uploadTitle: "Upload Payment Receipt",
    uploadBody: "Upload a clear image of your payment receipt.",
    choose: "Upload receipt",
    replace: "Replace",
    remove: "Remove",
    uploading: "Uploading…",
    receiptAlt: "Your payment receipt",
    senderTitle: "Sender / Account Details",
    senderBody: "Enter the details of the account that made the payment.",
    senderBank: { label: "Sender Bank Name", placeholder: "e.g. UBA, GTBank, Access Bank..." },
    senderName: { label: "Sender Account Name", placeholder: "e.g. John Doe" },
    senderNumber: { label: "Sender Account Number", placeholder: "e.g. 0123456789" },
    secureTitle: "Your payment information is securely handled by Kinkord.",
    secureBody: "We do not share your details with third parties.",
    cta: "Submit Payment for Verification",
    submitting: "Submitting…",
    errors: {
      receipt: "Upload your receipt.",
      uploading: "Wait for your receipt to finish uploading.",
      amount: "Enter the amount you paid.",
      reference: "Enter the payment reference.",
      bank: "Enter the bank you paid from.",
      name: "Enter the name on the account.",
      number: "Account numbers are 10 digits.",
    },
  },
  state: {
    submitted: {
      title: "Payment sent for verification",
      body: "We're checking your transfer against our statement. We'll let you know as soon as Silver is on.",
    },
    verified: {
      title: "Payment confirmed",
      body: "Silver Premium is active. Enjoy the full Kinkord experience.",
    },
    rejected: {
      title: "We couldn't confirm this payment",
      body: (reason: string) => reason,
    },
    expired: {
      title: "This payment has expired",
      body: "Start a new payment from the Silver page.",
    },
    back: "Back to Silver",
  },
} as const;
