export const WALLET_COPY = {
  testMode:
    "Test environment · Do not transfer real money. Bank details and balances are for testing only.",
  titles: {
    overview: "KinkCoins & Payment",
    buy: "Buy KinkCoins",
    history: "Transaction History",
    banks: "Bank Accounts",
    withdraw: "Withdraw / Redeem",
    pay: "Pay by Bank Transfer",
  },
  heading: "KinkCoins",
  subtitle: "Your wallet for gifts, creators and experiences within Kinkord.",
  back: "Back to wallet",
  menu: "Open menu",
  loading: "Loading your wallet…",
  retry: "Refresh",
  unavailable:
    "Transactions are unavailable until the lead configures NGN rates and the payment bank account.",
  actions: [
    {
      key: "buy",
      title: "Buy KinkCoins",
      description: "Pay by bank transfer. Coins arrive after verification.",
    },
    {
      key: "banks",
      title: "Bank Accounts",
      description: "Save and manage your withdrawal accounts.",
    },
    {
      key: "earn",
      title: "Earn KinkCoins",
      description: "Complete tasks, join events and get rewarded.",
    },
    {
      key: "history",
      title: "Transaction History",
      description: "Track purchases, withdrawals and admin decisions.",
    },
    {
      key: "convert",
      title: "Convert / Use KinkCoins",
      description: "Turn your coins into stars, crowns or other benefits.",
    },
    {
      key: "withdraw",
      title: "Withdraw / Redeem",
      description: "Request a transfer to one of your bank accounts.",
    },
  ],
  comingSoon: "Coming soon",
  labels: { coin: "Coins", star: "Stars", crown: "Crowns" },
  reserved: "Reserved for withdrawals",
  buy: "Buy now",
  minimum: "Minimum withdrawal",
  bank: "Bank name",
  holder: "Account holder name",
  number: "Account number",
  saveBank: "Save bank account",
  addBank: "Add bank account",
  default: "Default",
  makeDefault: "Set as default",
  remove: "Remove",
  noBanks: "No bank accounts saved",
  bankNotice:
    "Use an account in your name. Check every detail carefully; bank account ownership is not verified automatically.",
  noHistory: "No transactions yet",
  historyHint: "Your latest 200 purchases and withdrawals appear here.",
  resume: "Continue payment",
  review: "Review withdrawal",
  quantity: "Quantity to redeem",
  chooseBank: "Withdrawal account",
  available: "Available",
  estimate: "You will receive",
  fee: "Withdrawal fee: ₦0.00",
  confirm: "Submit withdrawal request",
  withdrawNotice:
    "Submitting reserves your coins. An admin must approve the request and transfer funds manually. A rejected request releases the coins back to your available balance.",
  submitted: "Withdrawal Submitted",
  processing:
    "Your request is awaiting admin approval. Funds are sent manually after approval. Timing depends on the team and your bank.",
  reference: "Transaction reference",
  home: "Back to home",
  history: "View transaction history",
  cancel: "Back",
  transfer:
    "Transfer the exact amount to this account, then upload proof. Your wallet is credited only after an admin verifies the payment.",
  amount: "Amount to transfer",
  sender: "Name on the sending bank account",
  senderReference: "Your bank transfer reference",
  receipt: "Receipt (JPEG, PNG or WebP, up to 10 MB)",
  submitProof: "Submit payment proof",
  waiting: "Your payment proof is awaiting admin verification.",
  failed: "This transaction was rejected. Read the reason below before starting again.",
  approved: "Your withdrawal is approved and awaiting a manual bank transfer.",
  paid: "The admin has recorded your bank transfer as paid.",
  verified: "Payment verified. Your wallet has been credited.",
  adminTitle: "Wallet Payments & Withdrawals",
  adminHint:
    "Verify incoming bank transfers, review withdrawals, and mark transfers paid after sending them manually.",
  settings: "Wallet rates (NGN per unit)",
  minimumSetting: "Minimum withdrawal (NGN)",
  enabled: "Enable purchases and withdrawals",
  saveSettings: "Save wallet settings",
  paymentBank: "Manage receiving bank account",
  incoming: "Coin purchases",
  outgoing: "Withdrawals",
  all: "All statuses",
  emptyQueue: "No requests match this filter.",
  verify: "Verify payment",
  approve: "Approve withdrawal",
  reject: "Reject request",
  markPaid: "Mark paid",
  reason: "Reason for rejection",
  bankReference: "Bank transfer reference",
  decisionConfirm: "Confirm decision",
  verifyHint:
    "Match this receipt and the amount to your bank statement before crediting the wallet.",
  approveHint:
    "Approval does not send money. The funds remain reserved until you record the manual transfer.",
  paidHint:
    "Only mark this request paid after sending the money to the account shown. Enter the actual bank transfer reference.",
  rejectHint: "Explain the rejection to the member. Reserved withdrawal coins will be returned.",
  saved: "Saved successfully.",
  defaultUpdated: "Default bank account updated.",
  bankRemoved: "Bank account removed.",
  purchaseRate: "Purchase",
  redeemRate: "Redemption",
  disabled: "Wallet transactions are disabled.",
} as const;
